### ISSUE TITLE
you broke bunch of my unit tests!!!!

### ISSUE THREAD

**Issue by awaragi** [rtyley/small-test-repo#30]
Hahaha. I have been using your repository as a sample git repository quick to clone in my unit tests for an app I am developing. All of my unit tests had 2 commits and 1 author! Teaches me to have external dependencies

**Comment by rtyley** [comment]
Oh! Uh, sorry about that- hopefully you can create your own repo for playing around with!

**Comment by awaragi** [comment]
No worry. it is your repository and it was the smallest I found on github so I took a shortcut. I will be creating mine. Thanks for a year of stability 😄
